[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Devin AI <158243242+devin-ai-integration[bot]@users.noreply.github.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.135.1"}
psycopg = {extras = ["binary"], version = "^3.3.3"}
yfinance = "^1.2.0"
pandas = "^3.0.1"
numpy = "^2.4.3"
ta = "^0.11.0"
websockets = "^16.0"
python-dotenv = "^1.2.2"
requests = "^2.32.5"
aiohttp = "^3.13.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
